BOOTSTRAP_SERVER="1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001"
LOCAL_PORT=5453
MONITOR_CONFIDENCE_FACTOR=10
MONITOR_MAX_CONFIDENCE=5
MONITOR_RETRIES=3
MONITOR_SLEEP_FACTOR=6

DOH_DOMAIN="cloudflare-dns.com"
DOH_PATH="/dns-query"
DOT_DOMAIN="1dot1dot1dot1.cloudflare-dns.com"

LAN_INTERFACE="lan"
WAN_INTERFACES="wan wan6 wwan wwan6"
